"""Примеры оружия: основная рука, вторая рука, двуручное."""

from __future__ import annotations

from typing import Any

from game.items.equipment.catalog._stub_utils import finalize_stub_list
from game.items.equipment.item_asset_paths import item_gear_png


def weapon_main_examples() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = [
        {
            "name": "Клинок нижней ступени",
            "kind": "weapon",
            "hand": "main",
            "rarity": "common",
            "attack": 7,
            "weapon_type": "blade",
            "enchant": 0,
            "summary": "Ровное лезвие для первых врагов.",
            "image_url": item_gear_png("catalog_wpn_main_01"),
        },
        {
            "name": "Копьё дозорного",
            "kind": "weapon",
            "hand": "main",
            "rarity": "common",
            "attack": 8,
            "weapon_type": "polearm",
            "enchant": 0,
            "summary": "Длинная древесина, острый наконечник.",
            "image_url": item_gear_png("catalog_wpn_main_02"),
        },
        {
            "name": "Топор дровосека башни",
            "kind": "weapon",
            "hand": "main",
            "rarity": "uncommon",
            "attack": 10,
            "weapon_type": "axe",
            "enchant": 0,
            "summary": "Тяжёлый размах — слабая броня ломается.",
            "image_url": item_gear_png("catalog_wpn_main_03"),
        },
        {
            "name": "Молот каменщика",
            "kind": "weapon",
            "hand": "main",
            "rarity": "uncommon",
            "attack": 9,
            "weapon_type": "hammer",
            "enchant": 0,
            "summary": "Глухой удар по плитам и панцирям.",
            "image_url": item_gear_png("catalog_wpn_main_04"),
        },
        {
            "name": "Лук заветной тропы",
            "kind": "weapon",
            "hand": "main",
            "rarity": "uncommon",
            "attack": 9,
            "weapon_type": "bow",
            "two_handed": True,
            "enchant": 0,
            "summary": "Двуручный — занимает основную руку полностью.",
            "image_url": item_gear_png("catalog_wpn_main_05"),
        },
        {
            "name": "Посох трещин",
            "kind": "weapon",
            "hand": "main",
            "rarity": "rare",
            "attack": 11,
            "weapon_type": "staff",
            "enchant": 1,
            "summary": "По древку бегут трещины света.",
            "image_url": item_gear_png("catalog_wpn_main_06"),
        },
        {
            "name": "Секира обета",
            "kind": "weapon",
            "hand": "main",
            "rarity": "rare",
            "attack": 13,
            "weapon_type": "axe",
            "enchant": 1,
            "summary": "Двойное лезвие — жертва и награда.",
            "image_url": item_gear_png("catalog_wpn_main_07"),
        },
        {
            "name": "Клинок серебряного рассвета",
            "kind": "weapon",
            "hand": "main",
            "rarity": "epic",
            "attack": 15,
            "weapon_type": "blade",
            "enchant": 2,
            "summary": "Отражает первый луч после ночного боя.",
            "image_url": item_gear_png("catalog_wpn_main_08"),
        },
    ]
    return finalize_stub_list(rows)


def weapon_offhand_examples() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = [
        {
            "name": "Кинжал второй руки",
            "kind": "weapon",
            "hand": "off",
            "rarity": "common",
            "attack": 5,
            "weapon_type": "dagger",
            "enchant": 0,
            "summary": "Лёгкий боковик.",
            "image_url": item_gear_png("catalog_wpn_off_01"),
        },
        {
            "name": "Кортик каната",
            "kind": "weapon",
            "hand": "off",
            "rarity": "common",
            "attack": 4,
            "weapon_type": "dagger",
            "enchant": 0,
            "summary": "Короткий, для рубки верёвок и сухожилий.",
            "image_url": item_gear_png("catalog_wpn_off_02"),
        },
        {
            "name": "Стилет тихого этажа",
            "kind": "weapon",
            "hand": "off",
            "rarity": "uncommon",
            "attack": 6,
            "weapon_type": "dagger",
            "enchant": 0,
            "dex": 1,
            "summary": "Почти невесомый.",
            "image_url": item_gear_png("catalog_wpn_off_03"),
        },
        {
            "name": "Крюк левой руки",
            "kind": "weapon",
            "hand": "off",
            "rarity": "uncommon",
            "attack": 6,
            "weapon_type": "dagger",
            "enchant": 0,
            "summary": "Изогнутое лезвие для удержания.",
            "image_url": item_gear_png("catalog_wpn_off_04"),
        },
        {
            "name": "Кинжал яда (пустой)",
            "kind": "weapon",
            "hand": "off",
            "rarity": "rare",
            "attack": 7,
            "weapon_type": "dagger",
            "enchant": 1,
            "summary": "Желоб под яд — сейчас пуст.",
            "image_url": item_gear_png("catalog_wpn_off_05"),
        },
        {
            "name": "Короткий клинок пары",
            "kind": "weapon",
            "hand": "off",
            "rarity": "rare",
            "attack": 8,
            "weapon_type": "blade",
            "enchant": 0,
            "summary": "Дополняет длинный клинок в основной руке.",
            "image_url": item_gear_png("catalog_wpn_off_06"),
        },
        {
            "name": "Булава второго удара",
            "kind": "weapon",
            "hand": "off",
            "rarity": "rare",
            "attack": 7,
            "weapon_type": "hammer",
            "enchant": 1,
            "summary": "Тяжёлый шар на короткой рукояти.",
            "image_url": item_gear_png("catalog_wpn_off_07"),
        },
        {
            "name": "Кинжал зеркальной воды",
            "kind": "weapon",
            "hand": "off",
            "rarity": "epic",
            "attack": 9,
            "weapon_type": "dagger",
            "enchant": 2,
            "luck": 1,
            "summary": "Лезвие отражает удар врага на миг.",
            "image_url": item_gear_png("catalog_wpn_off_08"),
        },
    ]
    return finalize_stub_list(rows)


def two_handed_weapon_examples() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = [
        {
            "name": "Двуручный меч новобранца",
            "kind": "weapon",
            "hand": "main",
            "two_handed": True,
            "rarity": "common",
            "attack": 12,
            "weapon_type": "blade",
            "enchant": 0,
            "summary": "Широкий клинок — вторая рука занята хватом.",
            "image_url": item_gear_png("catalog_wpn_2h_01"),
        },
        {
            "name": "Боевой посох дубины",
            "kind": "weapon",
            "hand": "main",
            "two_handed": True,
            "rarity": "common",
            "attack": 11,
            "weapon_type": "staff",
            "enchant": 0,
            "summary": "Толстое древко с металлическим навершием.",
            "image_url": item_gear_png("catalog_wpn_2h_02"),
        },
        {
            "name": "Секира сторожа ворот",
            "kind": "weapon",
            "hand": "main",
            "two_handed": True,
            "rarity": "uncommon",
            "attack": 14,
            "weapon_type": "axe",
            "enchant": 0,
            "summary": "Рубит щиты и когти.",
            "image_url": item_gear_png("catalog_wpn_2h_03"),
        },
        {
            "name": "Длинный лук кольца",
            "kind": "weapon",
            "hand": "main",
            "two_handed": True,
            "rarity": "uncommon",
            "attack": 13,
            "weapon_type": "bow",
            "enchant": 0,
            "summary": "Натяжение требует обеих рук.",
            "image_url": item_gear_png("catalog_wpn_2h_04"),
        },
        {
            "name": "Коса широкого среза",
            "kind": "weapon",
            "hand": "main",
            "two_handed": True,
            "rarity": "uncommon",
            "attack": 14,
            "weapon_type": "polearm",
            "enchant": 0,
            "summary": "Изогнутое лезвие как у жнеца.",
            "image_url": item_gear_png("catalog_wpn_2h_05"),
        },
        {
            "name": "Молот обрушения",
            "kind": "weapon",
            "hand": "main",
            "two_handed": True,
            "rarity": "rare",
            "attack": 17,
            "weapon_type": "hammer",
            "enchant": 1,
            "summary": "Один удар — трещины по камню.",
            "image_url": item_gear_png("catalog_wpn_2h_06"),
        },
        {
            "name": "Клеймор перекрёстка",
            "kind": "weapon",
            "hand": "main",
            "two_handed": True,
            "rarity": "rare",
            "attack": 18,
            "weapon_type": "blade",
            "enchant": 1,
            "summary": "Длинный клинок для размашистых дуг.",
            "image_url": item_gear_png("catalog_wpn_2h_07"),
        },
        {
            "name": "Двуручник ста колец",
            "kind": "weapon",
            "hand": "main",
            "two_handed": True,
            "rarity": "epic",
            "attack": 22,
            "weapon_type": "blade",
            "enchant": 2,
            "summary": "На полотне клинка — сто насечек побед.",
            "image_url": item_gear_png("catalog_wpn_2h_08"),
        },
    ]
    return finalize_stub_list(rows)
