"""
20 свитков зачарования алхимика: один рецепт на каждый уровень профессии 1..20.
Без чертежа — открываются уровнем профессии. Материалы: новая линейка + базовые травы.
"""

from __future__ import annotations

from typing import Any, Callable

PROF_ALC = "alchemist"

# (уровень, станок, герой, сек, опыт, craft_cost, результат-свиток)
# add_* ключи — как в workshop_enchant_service / item_data
_SCROLL_DEFS: list[dict[str, Any]] = [
    # 1–5
    {
        "id": "alch_ench_01",
        "name_ru": "Свиток: сияние стража I",
        "craft": {"light_dust": 5, "meadow_herb": 6},
        "ms": 1,
        "mc": 2,
        "sec": 420,
        "xp": 16,
        "res": {
            "name": "🧪 Свиток: сияние стража I",
            "kind": "consumable",
            "rarity": "common",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_armor": True,
            "min_alchemist_level_to_use": 1,
            "add_defense_flat": 3,
            "enchant_label_ru": "Солнечный настой I",
            "summary": "Алхимия: +броня. Требуется алх. 1+.",
        },
    },
    {
        "id": "alch_ench_02",
        "name_ru": "Свиток: кость ворона",
        "craft": {"raven_bone": 5, "moss_fungus": 5},
        "ms": 1,
        "mc": 3,
        "sec": 480,
        "xp": 18,
        "res": {
            "name": "🧪 Свиток: кость ворона",
            "kind": "consumable",
            "rarity": "common",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_armor": True,
            "min_alchemist_level_to_use": 2,
            "add_vit_flat": 2,
            "enchant_label_ru": "Тёмная жила I",
            "summary": "Алхимия: +живучесть на броню. Алх. 2+.",
        },
    },
    {
        "id": "alch_ench_03",
        "name_ru": "Свиток: искра шторма",
        "craft": {"storm_spark": 4, "blue_berry": 5},
        "ms": 1,
        "mc": 4,
        "sec": 560,
        "xp": 20,
        "res": {
            "name": "🧪 Свиток: искра шторма",
            "kind": "consumable",
            "rarity": "uncommon",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_weapon": True,
            "min_alchemist_level_to_use": 3,
            "add_fire_damage_bonus_pct": 5,
            "enchant_label_ru": "Грозовой масло I",
            "summary": "Оружие: +% к стихийному урону. Алх. 3+.",
        },
    },
    {
        "id": "alch_ench_04",
        "name_ru": "Свиток: пепел возрождения",
        "craft": {"phoenix_ash": 4, "spirit_pollen": 4},
        "ms": 1,
        "mc": 5,
        "sec": 640,
        "xp": 22,
        "res": {
            "name": "🧪 Свиток: пепел возрождения",
            "kind": "consumable",
            "rarity": "uncommon",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_armor": True,
            "min_alchemist_level_to_use": 4,
            "add_fire_resist_pct": 7,
            "enchant_label_ru": "Жар стойкости II",
            "summary": "Броня: сопротивление огню. Алх. 4+.",
        },
    },
    {
        "id": "alch_ench_05",
        "name_ru": "Свиток: морозная печать",
        "craft": {"frost_crystal": 4, "mandrake_root": 3},
        "ms": 1,
        "mc": 6,
        "sec": 720,
        "xp": 24,
        "res": {
            "name": "🧪 Свиток: морозная печать",
            "kind": "consumable",
            "rarity": "uncommon",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_armor": True,
            "min_alchemist_level_to_use": 5,
            "add_ice_resist_pct": 8,
            "enchant_label_ru": "Ледяной покров I",
            "summary": "Броня: сопротивление льду. Алх. 5+.",
        },
    },
    # 6–10
    {
        "id": "alch_ench_06",
        "name_ru": "Свиток: перо гарпии",
        "craft": {"harpy_feather": 4, "void_rose_thorn": 2},
        "ms": 2,
        "mc": 7,
        "sec": 880,
        "xp": 28,
        "res": {
            "name": "🧪 Свиток: перо гарпии",
            "kind": "consumable",
            "rarity": "rare",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_weapon": True,
            "min_alchemist_level_to_use": 6,
            "add_fire_damage_bonus_pct": 7,
            "add_str_flat": 1,
            "enchant_label_ru": "Вихрь клинка I",
            "summary": "Оружие: урон и немного силы. Алх. 6+.",
        },
    },
    {
        "id": "alch_ench_07",
        "name_ru": "Свиток: соль земли",
        "craft": {"earth_salt": 5, "golem_tear": 3},
        "ms": 2,
        "mc": 8,
        "sec": 960,
        "xp": 30,
        "res": {
            "name": "🧪 Свиток: соль земли",
            "kind": "consumable",
            "rarity": "rare",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_armor": True,
            "min_alchemist_level_to_use": 7,
            "add_defense_flat": 6,
            "add_poison_resist_pct": 6,
            "enchant_label_ru": "Минеральный каркас",
            "summary": "Броня: защита и яд. Алх. 7+.",
        },
    },
    {
        "id": "alch_ench_08",
        "name_ru": "Свиток: кровь камня",
        "craft": {"gargoyle_blood": 4, "basilisk_scale": 3},
        "ms": 2,
        "mc": 9,
        "sec": 1040,
        "xp": 32,
        "res": {
            "name": "🧪 Свиток: кровь камня",
            "kind": "consumable",
            "rarity": "rare",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_armor": True,
            "min_alchemist_level_to_use": 8,
            "add_dark_resist_pct": 8,
            "enchant_label_ru": "Тени отступают",
            "summary": "Броня: тьма. Алх. 8+.",
        },
    },
    {
        "id": "alch_ench_09",
        "name_ru": "Свиток: чешуя гидры",
        "craft": {"hydra_scale": 3, "moon_dust": 2},
        "ms": 2,
        "mc": 10,
        "sec": 1200,
        "xp": 36,
        "res": {
            "name": "🧪 Свиток: чешуя гидры",
            "kind": "consumable",
            "rarity": "epic",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_armor": True,
            "min_alchemist_level_to_use": 9,
            "add_poison_resist_pct": 10,
            "add_vit_flat": 3,
            "enchant_label_ru": "Ужас болот",
            "summary": "Броня: яд и живучесть. Алх. 9+.",
        },
    },
    {
        "id": "alch_ench_10",
        "name_ru": "Свиток: дух ветра",
        "craft": {"wind_spirit": 3, "phoenix_flower": 2},
        "ms": 2,
        "mc": 11,
        "sec": 1320,
        "xp": 38,
        "res": {
            "name": "🧪 Свиток: дух ветра",
            "kind": "consumable",
            "rarity": "epic",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_weapon": True,
            "min_alchemist_level_to_use": 10,
            "add_fire_damage_bonus_pct": 9,
            "add_dex_flat": 2,
            "enchant_label_ru": "Стремительный яд",
            "summary": "Оружие: урон и ловкость. Алх. 10+.",
        },
    },
    # 11–15
    {
        "id": "alch_ench_11",
        "name_ru": "Свиток: пламя змея",
        "craft": {"dragon_flame": 2, "void_rose_thorn": 4},
        "ms": 3,
        "mc": 12,
        "sec": 1600,
        "xp": 42,
        "res": {
            "name": "🧪 Свиток: пламя змея",
            "kind": "consumable",
            "rarity": "epic",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_armor": True,
            "min_alchemist_level_to_use": 11,
            "add_fire_resist_pct": 12,
            "add_defense_flat": 4,
            "enchant_label_ru": "Драконья чешуя",
            "summary": "Броня: огонь и плотность. Алх. 11+.",
        },
    },
    {
        "id": "alch_ench_12",
        "name_ru": "Свиток: лунная фильтрация",
        "craft": {"moon_dust": 4, "storm_spark": 4},
        "ms": 3,
        "mc": 13,
        "sec": 1680,
        "xp": 44,
        "res": {
            "name": "🧪 Свиток: лунная фильтрация",
            "kind": "consumable",
            "rarity": "epic",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_armor": True,
            "min_alchemist_level_to_use": 12,
            "add_lightning_resist_pct": 10,
            "enchant_label_ru": "Лунный громозащитник",
            "summary": "Броня: молния. Алх. 12+.",
        },
    },
    {
        "id": "alch_ench_13",
        "name_ru": "Свиток: эссенция бури",
        "craft": {"void_essence": 1, "storm_spark": 5, "harpy_feather": 3},
        "ms": 3,
        "mc": 14,
        "sec": 1900,
        "xp": 48,
        "res": {
            "name": "🧪 Свиток: эссенция бури",
            "kind": "consumable",
            "rarity": "epic",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_weapon": True,
            "min_alchemist_level_to_use": 13,
            "add_fire_damage_bonus_pct": 11,
            "enchant_label_ru": "Удар конденсатора",
            "summary": "Оружие: сильный стихийный бонус. Алх. 13+.",
        },
    },
    {
        "id": "alch_ench_14",
        "name_ru": "Свиток: якорь земли",
        "craft": {"earth_salt": 5, "basilisk_scale": 4, "light_dust": 6},
        "ms": 3,
        "mc": 15,
        "sec": 2000,
        "xp": 50,
        "res": {
            "name": "🧪 Свиток: якорь земли",
            "kind": "consumable",
            "rarity": "epic",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_armor": True,
            "min_alchemist_level_to_use": 14,
            "add_defense_flat": 10,
            "add_str_flat": 2,
            "enchant_label_ru": "Каменная решимость",
            "summary": "Броня: защита и сила. Алх. 14+.",
        },
    },
    {
        "id": "alch_ench_15",
        "name_ru": "Свиток: зеркало бездны",
        "craft": {"void_essence": 2, "gargoyle_blood": 4},
        "ms": 3,
        "mc": 16,
        "sec": 2200,
        "xp": 54,
        "res": {
            "name": "🧪 Свиток: зеркало бездны",
            "kind": "consumable",
            "rarity": "legendary",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_armor": True,
            "min_alchemist_level_to_use": 15,
            "add_dark_resist_pct": 12,
            "add_int_flat": 2,
            "enchant_label_ru": "Отражение тьмы",
            "summary": "Броня: тьма и интеллект. Алх. 15+.",
        },
    },
    # 16–20
    {
        "id": "alch_ench_16",
        "name_ru": "Свиток: чешуя шторма",
        "craft": {"hydra_scale": 4, "wind_spirit": 3},
        "ms": 4,
        "mc": 17,
        "sec": 2600,
        "xp": 58,
        "res": {
            "name": "🧪 Свиток: чешуя шторма",
            "kind": "consumable",
            "rarity": "legendary",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_armor": True,
            "min_alchemist_level_to_use": 16,
            "add_lightning_resist_pct": 12,
            "add_poison_resist_pct": 8,
            "enchant_label_ru": "Шторм и яд",
            "summary": "Броня: молния+яд. Алх. 16+.",
        },
    },
    {
        "id": "alch_ench_17",
        "name_ru": "Свиток: дыхание дракона",
        "craft": {"dragon_flame": 3, "phoenix_ash": 4},
        "ms": 4,
        "mc": 18,
        "sec": 2800,
        "xp": 62,
        "res": {
            "name": "🧪 Свиток: дыхание дракона",
            "kind": "consumable",
            "rarity": "legendary",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_weapon": True,
            "min_alchemist_level_to_use": 17,
            "add_fire_damage_bonus_pct": 14,
            "enchant_label_ru": "Огненная кара",
            "summary": "Оружие: максимальный стихийный бонус. Алх. 17+.",
        },
    },
    {
        "id": "alch_ench_18",
        "name_ru": "Свиток: ледяной трон",
        "craft": {"frost_crystal": 6, "quintessence": 1},
        "ms": 4,
        "mc": 18,
        "sec": 3000,
        "xp": 66,
        "res": {
            "name": "🧪 Свиток: ледяной трон",
            "kind": "consumable",
            "rarity": "legendary",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_armor": True,
            "min_alchemist_level_to_use": 18,
            "add_ice_resist_pct": 14,
            "add_defense_flat": 8,
            "enchant_label_ru": "Вечная стужа",
            "summary": "Броня: лёд и броня. Алх. 18+.",
        },
    },
    {
        "id": "alch_ench_19",
        "name_ru": "Свиток: квинтэссенция стража",
        "craft": {"quintessence": 1, "golden_apple": 1, "moon_dust": 4},
        "ms": 4,
        "mc": 19,
        "sec": 4200,
        "xp": 72,
        "res": {
            "name": "🧪 Свиток: квинтэссенция стража",
            "kind": "consumable",
            "rarity": "legendary",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_armor": True,
            "min_alchemist_level_to_use": 19,
            "add_fire_resist_pct": 8,
            "add_ice_resist_pct": 8,
            "add_lightning_resist_pct": 8,
            "add_poison_resist_pct": 8,
            "add_dark_resist_pct": 8,
            "enchant_label_ru": "Универсальный барьер",
            "summary": "Броня: ко всем стихиям понемногу. Алх. 19+.",
        },
    },
    {
        "id": "alch_ench_20",
        "name_ru": "Свиток: апофеоз алхимика",
        "craft": {"quintessence": 2, "dragon_flame": 2, "void_essence": 2},
        "ms": 5,
        "mc": 20,
        "sec": 5400,
        "xp": 80,
        "res": {
            "name": "🧪 Свиток: апофеоз алхимика",
            "kind": "consumable",
            "rarity": "legendary",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_weapon": True,
            "min_alchemist_level_to_use": 20,
            "add_fire_damage_bonus_pct": 16,
            "add_str_flat": 3,
            "add_int_flat": 3,
            "enchant_label_ru": "Вершина смесей",
            "summary": "Оружие: верхний стихийный бонус и статы. Алх. 20.",
        },
    },
]


def extend_recipes_with_alchemy_enchant_scrolls(reg_fn: Callable[[dict[str, Any]], dict[str, Any]], out_list: list) -> None:
    for i, spec in enumerate(_SCROLL_DEFS):
        lv = i + 1
        recipe = {
            "id": spec["id"],
            "name_ru": spec["name_ru"],
            "description": f"Свиток зачарования алхимика (ур. {lv}). Без отдельного чертежа.",
            "profession": PROF_ALC,
            "min_profession_level": lv,
            "min_station_level": spec["ms"],
            "min_character_level": spec["mc"],
            "cost": {},
            "craft_cost": dict(spec["craft"]),
            "forge_instant": False,
            "craft_seconds": int(spec["sec"]),
            "xp_reward": int(spec["xp"]),
            "requires_blueprint": False,
            "result": dict(spec["res"]),
        }
        out_list.append(reg_fn(recipe))
