"""
Рецепты крафта: городская кузня (мгновенно) и мастерская (таймеры, профессии 1–30).
Стоимость: craft_cost — именованные ремесленные материалы (слитки, травы, самоцветы).
cost оставлен пустым {}; заточка башни — отдельная система в кузнице.
forge_instant — мгновенный крафт в городской кузне.
"""

from __future__ import annotations

from typing import Any

from game.crafting.alchemy_enchant_scrolls import extend_recipes_with_alchemy_enchant_scrolls
from game.crafting.workshop_constants import max_profession_level

# Ключи профессий (мастерская)
PROF_BLACKSMITH = "blacksmith"
PROF_ALCHEMIST = "alchemist"
PROF_JEWELER = "jeweler"

PROFESSION_KEYS: tuple[str, ...] = (PROF_BLACKSMITH, PROF_ALCHEMIST, PROF_JEWELER)

_RECIPE_BY_ID: dict[str, dict[str, Any]] = {}


def _reg(r: dict[str, Any]) -> dict[str, Any]:
    rid = str(r["id"])
    _RECIPE_BY_ID[rid] = r
    return r


# --------- Мгновенные рецепты кузни (как раньше salve_basic / ring_siphon) ---------

_RECIPES_LIST: list[dict[str, Any]] = [
    _reg(
        {
            "id": "salve_basic",
            "name_ru": "Настой живучести",
            "description": "Простой HP-настой из сплавов башни.",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 1,
            "min_station_level": 1,
            "min_character_level": 1,
            "cost": {},
            "craft_cost": {"meadow_herb": 6, "moss_fungus": 2},
            "forge_instant": True,
            "craft_seconds": 120,
            "xp_reward": 12,
            "requires_blueprint": True,
            "result": {
                "name": "🧪 Настой живучести",
                "kind": "consumable",
                "rarity": "common",
                "use_tag": "heal_hp_pct",
                "use_value": 22,
                "summary": "В бою: восстанавливает процент от макс. HP.",
            },
        },
    ),
    _reg(
        {
            "id": "ring_siphon",
            "name_ru": "Перстень поглощения",
            "description": "Кольцо с лёгкой подпиткой от трофеев.",
            "profession": PROF_JEWELER,
            "min_profession_level": 1,
            "min_station_level": 1,
            "min_character_level": 1,
            "cost": {},
            "craft_cost": {"copper_dust": 5, "tiger_eye": 3},
            "forge_instant": True,
            "craft_seconds": 240,
            "xp_reward": 18,
            "requires_blueprint": True,
            "result": {
                "name": "💍 Перстень поглощения",
                "kind": "ring",
                "rarity": "uncommon",
                "defense": 4,
                "int": 3,
                "summary": "Ювелирная работа: немного защиты и интеллекта.",
            },
        },
    ),
    # Timed — только мастерская
    _reg(
        {
            "id": "iron_charm_loop",
            "name_ru": "Железное кольцо-основа",
            "description": "Базовая заготовка для украшений.",
            "profession": PROF_JEWELER,
            "min_profession_level": 1,
            "min_station_level": 1,
            "min_character_level": 1,
            "cost": {},
            "craft_cost": {"copper_dust": 4, "river_pearl": 2},
            "forge_instant": False,
            "craft_seconds": 180,
            "xp_reward": 10,
            "requires_blueprint": False,
            "result": {
                "name": "⭕ Железное кольцо",
                "kind": "ring",
                "rarity": "common",
                "defense": 2,
                "summary": "Грубая работа кузницы и ювелира.",
            },
        },
    ),
    _reg(
        {
            "id": "weak_blade_blank",
            "name_ru": "Заготовка клинка",
            "description": "Простой клинок без заточки.",
            "profession": PROF_BLACKSMITH,
            "min_profession_level": 1,
            "min_station_level": 1,
            "min_character_level": 1,
            "cost": {},
            "craft_cost": {"copper_ingot": 5, "iron_ingot": 3},
            "forge_instant": False,
            "craft_seconds": 420,
            "xp_reward": 14,
            "requires_blueprint": False,
            "result": {
                "name": "⚔️ Заготовка клинка",
                "kind": "weapon",
                "rarity": "common",
                "attack": 8,
                "summary": "Сырой клинок; заточку делай в кузнице.",
            },
        },
    ),
    _reg(
        {
            "id": "mana_drop_flask",
            "name_ru": "Капля маны (флакон)",
            "description": "Концентрированная капля эфира.",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 2,
            "min_station_level": 1,
            "min_character_level": 3,
            "cost": {},
            "craft_cost": {"blue_berry": 2, "meadow_herb": 3},
            "forge_instant": False,
            "craft_seconds": 300,
            "xp_reward": 16,
            "requires_blueprint": False,
            "result": {
                "name": "💧 Капля маны",
                "kind": "consumable",
                "rarity": "common",
                "use_tag": "heal_mp_pct",
                "use_value": 15,
                "summary": "В бою: восстанавливает процент MP.",
            },
        },
    ),
    _reg(
        {
            "id": "bp_tower_flame_blade",
            "name_ru": "Клинок пламени башни",
            "description": "Редкий чертёж: огненный клинок.",
            "profession": PROF_BLACKSMITH,
            "min_profession_level": 8,
            "min_station_level": 3,
            "min_character_level": 15,
            "cost": {},
            "craft_cost": {"dragon_bone": 1, "hardened_steel": 2, "mithril_ingot": 2, "obsidian": 1},
            "forge_instant": False,
            "craft_seconds": 3600,
            "xp_reward": 80,
            "requires_blueprint": True,
            "result": {
                "name": "🔥 Клинок пламени башни",
                "kind": "weapon",
                "rarity": "rare",
                "attack": 42,
                "summary": "Редкое оружие из чертежа мастерской.",
            },
        },
    ),
    _reg(
        {
            "id": "gem_socket_amulet",
            "name_ru": "Амулет с оправой",
            "description": "Ювелир: основа под самоцветы.",
            "profession": PROF_JEWELER,
            "min_profession_level": 5,
            "min_station_level": 2,
            "min_character_level": 10,
            "cost": {},
            "craft_cost": {"amber": 3, "moonstone": 3, "tiger_eye": 2},
            "forge_instant": False,
            "craft_seconds": 900,
            "xp_reward": 35,
            "requires_blueprint": False,
            "result": {
                "name": "📿 Амулет-основа",
                "kind": "amulet",
                "rarity": "uncommon",
                "defense": 12,
                "summary": "Качественная оправа; камни вставляются в кузнице.",
            },
        },
    ),
    _reg(
        {
            "id": "grand_elixir",
            "name_ru": "Большой эликсир",
            "description": "Сильное восстановление HP.",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 6,
            "min_station_level": 2,
            "min_character_level": 12,
            "cost": {},
            "craft_cost": {"mandrake_root": 4, "spirit_pollen": 2, "void_rose_thorn": 1},
            "forge_instant": False,
            "craft_seconds": 1200,
            "xp_reward": 45,
            "requires_blueprint": False,
            "result": {
                "name": "🧪 Большой эликсир",
                "kind": "consumable",
                "rarity": "uncommon",
                "use_tag": "heal_hp_pct",
                "use_value": 40,
                "summary": "Мощный процент HP в бою.",
            },
        },
    ),
    # --- Ювелир: руны ранга III / IV / V (пример: огонь) ---
    _reg(
        {
            "id": "jeweler_rune_fire_3",
            "name_ru": "Руна пламени III (ювелир)",
            "description": "Крафт руны 3 ранга. Требуется 5+ уровень ювелира.",
            "profession": PROF_JEWELER,
            "min_profession_level": 5,
            "min_station_level": 1,
            "min_character_level": 1,
            "cost": {},
            "craft_cost": {"amber": 2, "tiger_eye": 4},
            "forge_instant": False,
            "craft_seconds": 400,
            "xp_reward": 22,
            "requires_blueprint": False,
            "result": {
                "name": "🔥 Руна Пламени III",
                "kind": "rune",
                "rarity": "rare",
                "summary": "Вставь в оружие. Ранг III.",
                "rune": {"element": "fire", "rank": 3},
            },
        },
    ),
    _reg(
        {
            "id": "jeweler_rune_fire_4",
            "name_ru": "Руна пламени IV (ювелир)",
            "description": "Крафт руны 4 ранга. Требуется 10+ уровень ювелира.",
            "profession": PROF_JEWELER,
            "min_profession_level": 10,
            "min_station_level": 2,
            "min_character_level": 5,
            "cost": {},
            "craft_cost": {"blood_ruby": 2, "life_emerald": 1, "storm_sapphire": 2},
            "forge_instant": False,
            "craft_seconds": 800,
            "xp_reward": 40,
            "requires_blueprint": False,
            "result": {
                "name": "🔥 Руна Пламени IV",
                "kind": "rune",
                "rarity": "epic",
                "summary": "Вставь в оружие. Ранг IV.",
                "rune": {"element": "fire", "rank": 4},
            },
        },
    ),
    _reg(
        {
            "id": "jeweler_rune_fire_5",
            "name_ru": "Руна пламени V (ювелир)",
            "description": "Крафт руны 5 ранга. Только ювелир 20 уровня.",
            "profession": PROF_JEWELER,
            "min_profession_level": 20,
            "min_station_level": 4,
            "min_character_level": 10,
            "cost": {},
            "craft_cost": {"black_opal": 2, "cyclops_eye": 1, "void_diamond": 1},
            "forge_instant": False,
            "craft_seconds": 2400,
            "xp_reward": 90,
            "requires_blueprint": False,
            "result": {
                "name": "🔥 Руна Пламени V",
                "kind": "rune",
                "rarity": "legendary",
                "summary": "Вставь в оружие. Ранг V.",
                "rune": {"element": "fire", "rank": 5},
            },
        },
    ),
    # --- Алхимик: свитки зачарования (наложение на предмет в сумке) ---
    _reg(
        {
            "id": "alchemy_scroll_fire_shell_i",
            "name_ru": "Смола огнеупора I",
            "description": "Накладывает на доспех/шлем/перчатки/поножи сопротивление огню.",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 5,
            "min_station_level": 1,
            "min_character_level": 1,
            "cost": {},
            "craft_cost": {"meadow_herb": 4, "moss_fungus": 2},
            "forge_instant": False,
            "craft_seconds": 300,
            "xp_reward": 20,
            "requires_blueprint": False,
            "result": {
                "name": "🧪 Смола огнеупора I",
                "kind": "consumable",
                "rarity": "uncommon",
                "use_tag": "workshop_alchemy_enchant",
                "alchemy_enchant_armor": True,
                "add_fire_resist_pct": 6,
                "enchant_label_ru": "Огнеупор I",
                "summary": "Из сумки: наложи на предмет брони — +6% сопротивления огню (до 40%).",
            },
        },
    ),
    _reg(
        {
            "id": "alchemy_scroll_fire_shell_ii",
            "name_ru": "Смола огнеупора II",
            "description": "Сильнее защита от огненного урона на броне.",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 10,
            "min_station_level": 2,
            "min_character_level": 5,
            "cost": {},
            "craft_cost": {"blue_berry": 3, "mandrake_root": 2},
            "forge_instant": False,
            "craft_seconds": 600,
            "xp_reward": 35,
            "requires_blueprint": False,
            "result": {
                "name": "🧪 Смола огнеупора II",
                "kind": "consumable",
                "rarity": "rare",
                "use_tag": "workshop_alchemy_enchant",
                "alchemy_enchant_armor": True,
                "add_fire_resist_pct": 10,
                "enchant_label_ru": "Огнеупор II",
                "summary": "На броню в сумке: +10% сопротивления огню.",
            },
        },
    ),
    _reg(
        {
            "id": "alchemy_scroll_fire_shell_iii",
            "name_ru": "Смола огнеупора III",
            "description": "Максимальный алхимический огнеупор на латы.",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 15,
            "min_station_level": 3,
            "min_character_level": 10,
            "cost": {},
            "craft_cost": {"basilisk_scale": 1, "golem_tear": 2, "void_rose_thorn": 2},
            "forge_instant": False,
            "craft_seconds": 900,
            "xp_reward": 52,
            "requires_blueprint": False,
            "result": {
                "name": "🧪 Смола огнеупора III",
                "kind": "consumable",
                "rarity": "epic",
                "use_tag": "workshop_alchemy_enchant",
                "alchemy_enchant_armor": True,
                "add_fire_resist_pct": 14,
                "enchant_label_ru": "Огнеупор III",
                "summary": "На броню: +14% сопротивления огню (кап 40%).",
            },
        },
    ),
    _reg(
        {
            "id": "alchemy_scroll_flame_edge_i",
            "name_ru": "Эликсир пламенной кромки I",
            "description": "Усиливает огненный компонент урона оружия.",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 5,
            "min_station_level": 1,
            "min_character_level": 1,
            "cost": {},
            "craft_cost": {"meadow_herb": 3, "spirit_pollen": 2},
            "forge_instant": False,
            "craft_seconds": 300,
            "xp_reward": 20,
            "requires_blueprint": False,
            "result": {
                "name": "🧪 Эликсир пламенной кромки I",
                "kind": "consumable",
                "rarity": "uncommon",
                "use_tag": "workshop_alchemy_enchant",
                "alchemy_enchant_weapon": True,
                "add_fire_damage_bonus_pct": 5,
                "enchant_label_ru": "Пламя I",
                "summary": "Из сумки: наложи на оружие — +5% к огненному урону (до 40%).",
            },
        },
    ),
    _reg(
        {
            "id": "alchemy_scroll_flame_edge_ii",
            "name_ru": "Эликсир пламенной кромки II",
            "description": "Сильнее огненный урон по стихии.",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 10,
            "min_station_level": 2,
            "min_character_level": 5,
            "cost": {},
            "craft_cost": {"blue_berry": 2, "mandrake_root": 3},
            "forge_instant": False,
            "craft_seconds": 600,
            "xp_reward": 35,
            "requires_blueprint": False,
            "result": {
                "name": "🧪 Эликсир пламенной кромки II",
                "kind": "consumable",
                "rarity": "rare",
                "use_tag": "workshop_alchemy_enchant",
                "alchemy_enchant_weapon": True,
                "add_fire_damage_bonus_pct": 9,
                "enchant_label_ru": "Пламя II",
                "summary": "На оружие в сумке: +9% огненного урона.",
            },
        },
    ),
    _reg(
        {
            "id": "alchemy_scroll_flame_edge_iii",
            "name_ru": "Эликсир пламенной кромки III",
            "description": "Вершина алхимического усиления оружия огнём.",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 15,
            "min_station_level": 3,
            "min_character_level": 10,
            "cost": {},
            "craft_cost": {"basilisk_scale": 1, "moon_dust": 2, "phoenix_flower": 1},
            "forge_instant": False,
            "craft_seconds": 900,
            "xp_reward": 52,
            "requires_blueprint": False,
            "result": {
                "name": "🧪 Эликсир пламенной кромки III",
                "kind": "consumable",
                "rarity": "epic",
                "use_tag": "workshop_alchemy_enchant",
                "alchemy_enchant_weapon": True,
                "add_fire_damage_bonus_pct": 13,
                "enchant_label_ru": "Пламя III",
                "summary": "На оружие: +13% огненного урона (кап 40%).",
            },
        },
    ),
    # «Зачарование» алхимика — кольца-сигилы на 10 / 15 / 20 ур. профессии
    _reg(
        {
            "id": "alchemy_sigil_ring_t1",
            "name_ru": "Печать алхимика I",
            "description": "Кольцо с усилением (уровень алхимика 10+).",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 10,
            "min_station_level": 2,
            "min_character_level": 8,
            "cost": {},
            "craft_cost": {"mandrake_root": 4, "spirit_pollen": 2, "void_rose_thorn": 1},
            "forge_instant": False,
            "craft_seconds": 600,
            "xp_reward": 35,
            "requires_blueprint": False,
            "result": {
                "name": "💍 Печать алхимика I",
                "kind": "ring",
                "rarity": "rare",
                "defense": 8,
                "str": 4,
                "int": 4,
                "alchemy_sigil_tier": 1,
                "fire_damage_bonus_pct": 5,
                "summary": "Зачарование I: статы и +5% огненного урона.",
            },
        },
    ),
    _reg(
        {
            "id": "alchemy_sigil_ring_t2",
            "name_ru": "Печать алхимика II",
            "description": "Сильнее зачарование (алхимик 15+).",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 15,
            "min_station_level": 3,
            "min_character_level": 12,
            "cost": {},
            "craft_cost": {"moon_dust": 2, "phoenix_flower": 2, "void_essence": 1},
            "forge_instant": False,
            "craft_seconds": 900,
            "xp_reward": 55,
            "requires_blueprint": False,
            "result": {
                "name": "💍 Печать алхимика II",
                "kind": "ring",
                "rarity": "epic",
                "defense": 14,
                "str": 7,
                "int": 7,
                "alchemy_sigil_tier": 2,
                "fire_damage_bonus_pct": 10,
                "summary": "Зачарование II: статы и +10% огненного урона.",
            },
        },
    ),
    _reg(
        {
            "id": "alchemy_sigil_ring_t3",
            "name_ru": "Печать алхимика III",
            "description": "Вершина зачарования (алхимик 20).",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 20,
            "min_station_level": 4,
            "min_character_level": 18,
            "cost": {},
            "craft_cost": {"golden_apple": 1, "phoenix_flower": 1, "void_essence": 2},
            "forge_instant": False,
            "craft_seconds": 1800,
            "xp_reward": 85,
            "requires_blueprint": False,
            "result": {
                "name": "💍 Печать алхимика III",
                "kind": "ring",
                "rarity": "legendary",
                "defense": 22,
                "str": 12,
                "int": 12,
                "alchemy_sigil_tier": 3,
                "fire_damage_bonus_pct": 15,
                "summary": "Зачарование III: статы и +15% огненного урона.",
            },
        },
    ),
    # Кузнец: уникальный легендарный предмет (чертёж + высокий уровень)
    _reg(
        {
            "id": "legend_blade_forge",
            "name_ru": "Легендарная заготовка клинка",
            "description": "Уникальный крафт — только для опытного кузнеца (20+).",
            "profession": PROF_BLACKSMITH,
            "min_profession_level": 20,
            "min_station_level": 4,
            "min_character_level": 18,
            "cost": {},
            "craft_cost": {"adamantite": 2, "skysteel": 2, "titan_blood": 1},
            
            "forge_instant": False,
            "craft_seconds": 7200,
            "xp_reward": 120,
            "requires_blueprint": True,
            "result": {
                "name": "⚔️ Легендарная сталь башни",
                "kind": "weapon",
                "rarity": "legendary",
                "attack": 55,
                "unique_forge_tag": "tower_legend_blade",
                "summary": "Уникальное оружие мастерской. Звёзды при сборе.",
            },
        },
    ),
    # --- Кузнец: слоты брони + сталь/мифрил из гачи ---
    _reg(
        {
            "id": "smith_steel_cuirass",
            "name_ru": "Стальной нагрудник",
            "description": "Нагрудник из стали башни.",
            "profession": PROF_BLACKSMITH,
            "min_profession_level": 3,
            "min_station_level": 1,
            "min_character_level": 5,
            "cost": {},
            "craft_cost": {"iron_ingot": 4, "steel_ingot": 5},
            
            "forge_instant": False,
            "craft_seconds": 900,
            "xp_reward": 22,
            "requires_blueprint": False,
            "result": {
                "name": "🦺 Стальной нагрудник",
                "kind": "armor",
                "rarity": "uncommon",
                "defense": 18,
                "summary": "Крафт: стальные слитки + материалы заточки.",
            },
        },
    ),
    _reg(
        {
            "id": "smith_bronze_greaves",
            "name_ru": "Бронзовые поножи",
            "description": "Тяжёлые поножи.",
            "profession": PROF_BLACKSMITH,
            "min_profession_level": 4,
            "min_station_level": 1,
            "min_character_level": 6,
            "cost": {},
            "craft_cost": {"copper_ingot": 6, "iron_ingot": 4},
            
            "forge_instant": False,
            "craft_seconds": 780,
            "xp_reward": 24,
            "requires_blueprint": False,
            "result": {
                "name": "👖 Бронзовые поножи",
                "kind": "pants",
                "rarity": "uncommon",
                "defense": 14,
                "summary": "Бронзовые слитки и базовые материалы.",
            },
        },
    ),
    _reg(
        {
            "id": "smith_silver_gauntlets",
            "name_ru": "Серебряные латы рук",
            "description": "Перчатки из серебристого сплава.",
            "profession": PROF_BLACKSMITH,
            "min_profession_level": 5,
            "min_station_level": 2,
            "min_character_level": 8,
            "cost": {},
            "craft_cost": {"hardened_steel": 2, "silver_ingot": 4},
            
            "forge_instant": False,
            "craft_seconds": 960,
            "xp_reward": 30,
            "requires_blueprint": False,
            "result": {
                "name": "🧤 Серебряные перчатки",
                "kind": "gloves",
                "rarity": "rare",
                "defense": 12,
                "attack": 4,
                "summary": "Серебряные слитки и редкие материалы.",
            },
        },
    ),
    _reg(
        {
            "id": "smith_mithril_helm",
            "name_ru": "Мифриловый шлем",
            "description": "Редкий шлем дальних этажей.",
            "profession": PROF_BLACKSMITH,
            "min_profession_level": 12,
            "min_station_level": 3,
            "min_character_level": 14,
            "cost": {},
            "craft_cost": {"dark_steel": 2, "dragon_bone": 1, "mithril_ingot": 3},
            
            "forge_instant": False,
            "craft_seconds": 2400,
            "xp_reward": 62,
            "requires_blueprint": False,
            "result": {
                "name": "⛑️ Мифриловый шлем",
                "kind": "helmet",
                "rarity": "epic",
                "defense": 28,
                "summary": "Мифриловые слитки из гачи.",
            },
        },
    ),
    _reg(
        {
            "id": "bp_adamant_bracers",
            "name_ru": "Чертёж: адамантовые наручи",
            "description": "Редкий чертёж тяжёлых наручей.",
            "profession": PROF_BLACKSMITH,
            "min_profession_level": 18,
            "min_station_level": 4,
            "min_character_level": 16,
            "cost": {},
            "craft_cost": {"adamantite": 2, "obsidian": 2, "titan_blood": 1},
            
            "forge_instant": False,
            "craft_seconds": 5400,
            "xp_reward": 95,
            "requires_blueprint": True,
            "result": {
                "name": "🧤 Адамантовые наручи",
                "kind": "gloves",
                "rarity": "legendary",
                "defense": 22,
                "attack": 18,
                "summary": "Чертёж из гачи; адамантит и топ материалы.",
            },
        },
    ),
    # --- Ювелир: кольца и амулеты ---
    _reg(
        {
            "id": "jeweler_quartz_band",
            "name_ru": "Кварцевое кольцо",
            "description": "Простое кольцо с огранкой.",
            "profession": PROF_JEWELER,
            "min_profession_level": 2,
            "min_station_level": 1,
            "min_character_level": 3,
            "cost": {},
            "craft_cost": {"copper_dust": 4, "tiger_eye": 2},
            
            "forge_instant": False,
            "craft_seconds": 420,
            "xp_reward": 18,
            "requires_blueprint": False,
            "result": {
                "name": "💍 Кварцевое кольцо",
                "kind": "ring",
                "rarity": "uncommon",
                "defense": 6,
                "int": 5,
                "summary": "Камни из гачи ювелира.",
            },
        },
    ),
    _reg(
        {
            "id": "jeweler_sapphire_loop",
            "name_ru": "Сапфировое кольцо",
            "description": "Кольцо с синим камнем.",
            "profession": PROF_JEWELER,
            "min_profession_level": 8,
            "min_station_level": 2,
            "min_character_level": 10,
            "cost": {},
            "craft_cost": {"moonstone": 2, "storm_sapphire": 3},
            
            "forge_instant": False,
            "craft_seconds": 1200,
            "xp_reward": 42,
            "requires_blueprint": False,
            "result": {
                "name": "💍 Сапфировое кольцо",
                "kind": "ring",
                "rarity": "rare",
                "defense": 10,
                "dex": 8,
                "summary": "Осколки сапфира.",
            },
        },
    ),
    _reg(
        {
            "id": "jeweler_ruby_pendant",
            "name_ru": "Рубиновый медальон",
            "description": "Амулет с ядром рубина.",
            "profession": PROF_JEWELER,
            "min_profession_level": 11,
            "min_station_level": 2,
            "min_character_level": 12,
            "cost": {},
            "craft_cost": {"blood_ruby": 3, "life_emerald": 2},
            
            "forge_instant": False,
            "craft_seconds": 1800,
            "xp_reward": 55,
            "requires_blueprint": False,
            "result": {
                "name": "📿 Рубиновый медальон",
                "kind": "amulet",
                "rarity": "epic",
                "defense": 16,
                "vit": 10,
                "summary": "Рубиновое ядро.",
            },
        },
    ),
    _reg(
        {
            "id": "bp_void_wedding_band",
            "name_ru": "Чертёж: кольцо пустоты",
            "description": "Легендарный чертёж — только с чертежом.",
            "profession": PROF_JEWELER,
            "min_profession_level": 20,
            "min_station_level": 4,
            "min_character_level": 18,
            "cost": {},
            "craft_cost": {"star_heart": 1, "void_diamond": 2},
            
            "forge_instant": False,
            "craft_seconds": 6000,
            "xp_reward": 110,
            "requires_blueprint": True,
            "result": {
                "name": "💍 Кольцо пустоты",
                "kind": "ring",
                "rarity": "legendary",
                "defense": 20,
                "int": 15,
                "dex": 12,
                "summary": "Кристалл пустоты и чертёж из гачи.",
            },
        },
    ),
    # --- Алхимик: зелья и смолы с реагентами ---
    _reg(
        {
            "id": "alchemy_swift_tonic",
            "name_ru": "Тоник стремительности",
            "description": "Небольшой буст скорости реакции в бою.",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 3,
            "min_station_level": 1,
            "min_character_level": 4,
            "cost": {},
            "craft_cost": {"meadow_herb": 5, "moss_fungus": 2},
            
            "forge_instant": False,
            "craft_seconds": 360,
            "xp_reward": 16,
            "requires_blueprint": False,
            "result": {
                "name": "🧪 Тоник стремительности",
                "kind": "consumable",
                "rarity": "common",
                "use_tag": "heal_hp_pct",
                "use_value": 18,
                "summary": "Пучок трав из гачи.",
            },
        },
    ),
    _reg(
        {
            "id": "alchemy_arcane_philter",
            "name_ru": "Фильтр арканы",
            "description": "Восстановление маны сильнее базового.",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 7,
            "min_station_level": 2,
            "min_character_level": 9,
            "cost": {},
            "craft_cost": {"blue_berry": 4, "mandrake_root": 2, "spirit_pollen": 1},
            
            "forge_instant": False,
            "craft_seconds": 720,
            "xp_reward": 32,
            "requires_blueprint": False,
            "result": {
                "name": "🧪 Фильтр арканы",
                "kind": "consumable",
                "rarity": "uncommon",
                "use_tag": "heal_mp_pct",
                "use_value": 28,
                "summary": "Роса эссенции и соль.",
            },
        },
    ),
    _reg(
        {
            "id": "alchemy_dragon_serum",
            "name_ru": "Сыворотка дракона",
            "description": "Мощное зелье — редкое сырьё.",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 16,
            "min_station_level": 3,
            "min_character_level": 14,
            "cost": {},
            "craft_cost": {"moon_dust": 3, "phoenix_flower": 2, "void_essence": 1},
            
            "forge_instant": False,
            "craft_seconds": 3200,
            "xp_reward": 72,
            "requires_blueprint": False,
            "result": {
                "name": "🧪 Сыворотка дракона",
                "kind": "consumable",
                "rarity": "epic",
                "use_tag": "heal_hp_pct",
                "use_value": 55,
                "summary": "Желчь дракона и пыль философа.",
            },
        },
    ),
    _reg(
        {
            "id": "bp_alchemy_sun_elixir",
            "name_ru": "Чертёж: эликсир солнца",
            "description": "Редкий чертёж мощного лечения.",
            "profession": PROF_ALCHEMIST,
            "min_profession_level": 14,
            "min_station_level": 3,
            "min_character_level": 12,
            "cost": {},
            "craft_cost": {"golden_apple": 1, "phoenix_flower": 2, "void_essence": 1},
            
            "forge_instant": False,
            "craft_seconds": 4800,
            "xp_reward": 88,
            "requires_blueprint": True,
            "result": {
                "name": "🧪 Эликсир солнца",
                "kind": "consumable",
                "rarity": "legendary",
                "use_tag": "heal_hp_pct",
                "use_value": 70,
                "summary": "Чертёж из гачи; топ реагенты.",
            },
        },
    ),

_reg(
    {
        "id": "bp_sk_chain_hauberk",
        "name_ru": "Чертёж: кольчужный хауберк",
        "description": "Медь и железо.",
        "profession": "blacksmith",
        "min_profession_level": 4,
        "min_station_level": 1,
        "min_character_level": 6,
        "cost": {},
        "craft_cost": {"copper_ingot": 8, "iron_ingot": 5, "steel_ingot": 3},
        "forge_instant": False,
        "craft_seconds": 1200,
        "xp_reward": 28,
        "requires_blueprint": True,
        "result": {
            "name": "🦺 Кольчужный хауберк",
            "kind": "armor",
            "rarity": "uncommon",
            "defense": 22,
            "summary": "Чертёж кузнеца.",
        },
    },
),

_reg(
    {
        "id": "bp_sk_iron_gladius",
        "name_ru": "Чертёж: железный гладиус",
        "description": "Короткий клинок.",
        "profession": "blacksmith",
        "min_profession_level": 3,
        "min_station_level": 1,
        "min_character_level": 5,
        "cost": {},
        "craft_cost": {"iron_ingot": 7, "steel_ingot": 4},
        "forge_instant": False,
        "craft_seconds": 1100,
        "xp_reward": 26,
        "requires_blueprint": True,
        "result": {
            "name": "⚔️ Железный гладиус",
            "kind": "weapon",
            "rarity": "uncommon",
            "attack": 22,
            "summary": "Чертёж кузнеца.",
        },
    },
),

_reg(
    {
        "id": "bp_sk_silver_kite",
        "name_ru": "Чертёж: серебряный щит",
        "description": "Серебро и сталь.",
        "profession": "blacksmith",
        "min_profession_level": 6,
        "min_station_level": 2,
        "min_character_level": 9,
        "cost": {},
        "craft_cost": {"hardened_steel": 4, "silver_ingot": 6},
        "forge_instant": False,
        "craft_seconds": 2000,
        "xp_reward": 44,
        "requires_blueprint": True,
        "result": {
            "name": "🛡️ Серебряный щит",
            "kind": "shield",
            "rarity": "rare",
            "defense": 35,
            "summary": "Чертёж кузнеца.",
        },
    },
),

_reg(
    {
        "id": "bp_sk_dark_longsword",
        "name_ru": "Чертёж: меч тёмной стали",
        "description": "Тёмная сталь.",
        "profession": "blacksmith",
        "min_profession_level": 10,
        "min_station_level": 2,
        "min_character_level": 12,
        "cost": {},
        "craft_cost": {"dark_steel": 4, "dragon_bone": 1, "mithril_ingot": 2},
        "forge_instant": False,
        "craft_seconds": 2800,
        "xp_reward": 58,
        "requires_blueprint": True,
        "result": {
            "name": "⚔️ Меч тёмной стали",
            "kind": "weapon",
            "rarity": "epic",
            "attack": 48,
            "summary": "Чертёж кузнеца.",
        },
    },
),

_reg(
    {
        "id": "bp_sk_dragon_gorget",
        "name_ru": "Чертёж: горжет из кости дракона",
        "description": "Кость и обсидиан.",
        "profession": "blacksmith",
        "min_profession_level": 11,
        "min_station_level": 3,
        "min_character_level": 13,
        "cost": {},
        "craft_cost": {"dragon_bone": 4, "obsidian": 3},
        "forge_instant": False,
        "craft_seconds": 3200,
        "xp_reward": 64,
        "requires_blueprint": True,
        "result": {
            "name": "⛑️ Горжет из кости дракона",
            "kind": "helmet",
            "rarity": "epic",
            "defense": 32,
            "summary": "Чертёж кузнеца.",
        },
    },
),

_reg(
    {
        "id": "bp_sk_obsidian_greaves",
        "name_ru": "Чертёж: обсидиановые поножи",
        "description": "Вулканическое стекло.",
        "profession": "blacksmith",
        "min_profession_level": 9,
        "min_station_level": 2,
        "min_character_level": 11,
        "cost": {},
        "craft_cost": {"hardened_steel": 3, "obsidian": 5},
        "forge_instant": False,
        "craft_seconds": 2600,
        "xp_reward": 52,
        "requires_blueprint": True,
        "result": {
            "name": "👖 Обсидиановые поножи",
            "kind": "pants",
            "rarity": "rare",
            "defense": 26,
            "summary": "Чертёж кузнеца.",
        },
    },
),

_reg(
    {
        "id": "bp_sk_skysteel_spear",
        "name_ru": "Чертёж: копьё небесной стали",
        "description": "Небесное железо.",
        "profession": "blacksmith",
        "min_profession_level": 14,
        "min_station_level": 3,
        "min_character_level": 16,
        "cost": {},
        "craft_cost": {"mithril_ingot": 3, "silver_ingot": 4, "skysteel": 3},
        "forge_instant": False,
        "craft_seconds": 4200,
        "xp_reward": 78,
        "requires_blueprint": True,
        "result": {
            "name": "🔱 Копьё небесной стали",
            "kind": "weapon",
            "rarity": "legendary",
            "attack": 52,
            "summary": "Чертёж кузнеца.",
        },
    },
),

_reg(
    {
        "id": "bp_sk_adamant_helm",
        "name_ru": "Чертёж: шлем из адамантия",
        "description": "Топ металлов.",
        "profession": "blacksmith",
        "min_profession_level": 17,
        "min_station_level": 4,
        "min_character_level": 17,
        "cost": {},
        "craft_cost": {"adamantite": 2, "dragon_bone": 3, "skysteel": 2},
        "forge_instant": False,
        "craft_seconds": 5600,
        "xp_reward": 92,
        "requires_blueprint": True,
        "result": {
            "name": "⛑️ Шлем из адамантия",
            "kind": "helmet",
            "rarity": "legendary",
            "defense": 38,
            "summary": "Чертёж кузнеца.",
        },
    },
),

_reg(
    {
        "id": "bp_sk_titan_greataxe",
        "name_ru": "Чертёж: секира крови титана",
        "description": "Кровь титана.",
        "profession": "blacksmith",
        "min_profession_level": 19,
        "min_station_level": 4,
        "min_character_level": 18,
        "cost": {},
        "craft_cost": {"adamantite": 2, "skysteel": 2, "titan_blood": 2},
        "forge_instant": False,
        "craft_seconds": 6800,
        "xp_reward": 105,
        "requires_blueprint": True,
        "result": {
            "name": "🪓 Секира крови титана",
            "kind": "weapon",
            "rarity": "legendary",
            "attack": 58,
            "summary": "Чертёж кузнеца.",
        },
    },
),

_reg(
    {
        "id": "bp_sk_mithril_fullplate",
        "name_ru": "Чертёж: полный латник мифрила",
        "description": "Мифрил.",
        "profession": "blacksmith",
        "min_profession_level": 13,
        "min_station_level": 3,
        "min_character_level": 15,
        "cost": {},
        "craft_cost": {"dark_steel": 4, "mithril_ingot": 6},
        "forge_instant": False,
        "craft_seconds": 4800,
        "xp_reward": 74,
        "requires_blueprint": True,
        "result": {
            "name": "🦺 Полный латник мифрила",
            "kind": "armor",
            "rarity": "epic",
            "defense": 42,
            "summary": "Чертёж кузнеца.",
        },
    },
),

_reg(
    {
        "id": "bp_sk_flame_core_blade",
        "name_ru": "Чертёж: клинок огненного ядра",
        "description": "Кость дракона.",
        "profession": "blacksmith",
        "min_profession_level": 12,
        "min_station_level": 3,
        "min_character_level": 14,
        "cost": {},
        "craft_cost": {"dragon_bone": 3, "mithril_ingot": 2, "obsidian": 4},
        "forge_instant": False,
        "craft_seconds": 4000,
        "xp_reward": 68,
        "requires_blueprint": True,
        "result": {
            "name": "🔥 Клинок огненного ядра",
            "kind": "weapon",
            "rarity": "epic",
            "attack": 46,
            "summary": "Чертёж кузнеца.",
        },
    },
),

_reg(
    {
        "id": "bp_sk_storm_breaker",
        "name_ru": "Чертёж: грозолом",
        "description": "Небесная сталь.",
        "profession": "blacksmith",
        "min_profession_level": 15,
        "min_station_level": 3,
        "min_character_level": 16,
        "cost": {},
        "craft_cost": {"dragon_bone": 2, "mithril_ingot": 3, "skysteel": 4},
        "forge_instant": False,
        "craft_seconds": 4500,
        "xp_reward": 82,
        "requires_blueprint": True,
        "result": {
            "name": "⚔️ Грозолом",
            "kind": "weapon",
            "rarity": "legendary",
            "attack": 54,
            "summary": "Чертёж кузнеца.",
        },
    },
),

_reg(
    {
        "id": "bp_sk_void_edge",
        "name_ru": "Чертёж: кромка пустоты",
        "description": "Обсидиан.",
        "profession": "blacksmith",
        "min_profession_level": 11,
        "min_station_level": 3,
        "min_character_level": 13,
        "cost": {},
        "craft_cost": {"dark_steel": 4, "obsidian": 6},
        "forge_instant": False,
        "craft_seconds": 3600,
        "xp_reward": 60,
        "requires_blueprint": True,
        "result": {
            "name": "⚔️ Кромка пустоты",
            "kind": "weapon",
            "rarity": "epic",
            "attack": 44,
            "summary": "Чертёж кузнеца.",
        },
    },
),

_reg(
    {
        "id": "bp_sk_warden_gauntlets",
        "name_ru": "Чертёж: рукавицы стража",
        "description": "Закалённая сталь.",
        "profession": "blacksmith",
        "min_profession_level": 7,
        "min_station_level": 2,
        "min_character_level": 10,
        "cost": {},
        "craft_cost": {"hardened_steel": 5, "silver_ingot": 4},
        "forge_instant": False,
        "craft_seconds": 2200,
        "xp_reward": 46,
        "requires_blueprint": True,
        "result": {
            "name": "🧤 Рукавицы стража",
            "kind": "gloves",
            "rarity": "rare",
            "defense": 16,
            "attack": 6,
            "summary": "Чертёж кузнеца.",
        },
    },
),

_reg(
    {
        "id": "bp_sk_starfall_blade",
        "name_ru": "Чертёж: клинок звездопада",
        "description": "Адамантий.",
        "profession": "blacksmith",
        "min_profession_level": 20,
        "min_station_level": 4,
        "min_character_level": 19,
        "cost": {},
        "craft_cost": {"adamantite": 3, "dragon_bone": 2, "titan_blood": 1},
        "forge_instant": False,
        "craft_seconds": 7200,
        "xp_reward": 118,
        "requires_blueprint": True,
        "result": {
            "name": "⚔️ Клинок звездопада",
            "kind": "weapon",
            "rarity": "legendary",
            "attack": 60,
            "summary": "Чертёж кузнеца.",
        },
    },
),

_reg(
    {
        "id": "bp_al_healing_draught",
        "name_ru": "Чертёж: целительная настойка",
        "description": "Травы.",
        "profession": "alchemist",
        "min_profession_level": 2,
        "min_station_level": 1,
        "min_character_level": 4,
        "cost": {},
        "craft_cost": {"blue_berry": 3, "meadow_herb": 8},
        "forge_instant": False,
        "craft_seconds": 400,
        "xp_reward": 18,
        "requires_blueprint": True,
        "result": {
            "name": "🧪 Целительная настойка",
            "kind": "consumable",
            "rarity": "common",
            "use_tag": "heal_hp_pct",
            "use_value": 25,
            "summary": "Чертёж алхимика.",
        },
    },
),

_reg(
    {
        "id": "bp_al_mana_star",
        "name_ru": "Чертёж: звезда маны",
        "description": "Пыльца.",
        "profession": "alchemist",
        "min_profession_level": 3,
        "min_station_level": 1,
        "min_character_level": 5,
        "cost": {},
        "craft_cost": {"moss_fungus": 4, "spirit_pollen": 5},
        "forge_instant": False,
        "craft_seconds": 500,
        "xp_reward": 20,
        "requires_blueprint": True,
        "result": {
            "name": "🧪 Звезда маны",
            "kind": "consumable",
            "rarity": "common",
            "use_tag": "heal_mp_pct",
            "use_value": 20,
            "summary": "Чертёж алхимика.",
        },
    },
),

_reg(
    {
        "id": "bp_al_mandrake_tonic",
        "name_ru": "Чертёж: тоник мандрагоры",
        "description": "Корень.",
        "profession": "alchemist",
        "min_profession_level": 5,
        "min_station_level": 1,
        "min_character_level": 7,
        "cost": {},
        "craft_cost": {"mandrake_root": 5, "void_rose_thorn": 2},
        "forge_instant": False,
        "craft_seconds": 800,
        "xp_reward": 28,
        "requires_blueprint": True,
        "result": {
            "name": "🧪 Тоник мандрагоры",
            "kind": "consumable",
            "rarity": "uncommon",
            "use_tag": "heal_hp_pct",
            "use_value": 32,
            "summary": "Чертёж алхимика.",
        },
    },
),

_reg(
    {
        "id": "bp_al_golem_elixir",
        "name_ru": "Чертёж: эликсир голема",
        "description": "Слеза голема.",
        "profession": "alchemist",
        "min_profession_level": 8,
        "min_station_level": 2,
        "min_character_level": 10,
        "cost": {},
        "craft_cost": {"basilisk_scale": 3, "golem_tear": 4},
        "forge_instant": False,
        "craft_seconds": 1400,
        "xp_reward": 38,
        "requires_blueprint": True,
        "result": {
            "name": "🧪 Эликсир голема",
            "kind": "consumable",
            "rarity": "rare",
            "use_tag": "heal_hp_pct",
            "use_value": 42,
            "summary": "Чертёж алхимика.",
        },
    },
),

_reg(
    {
        "id": "bp_al_moon_veil",
        "name_ru": "Чертёж: покров луны",
        "description": "Лунная пыль.",
        "profession": "alchemist",
        "min_profession_level": 9,
        "min_station_level": 2,
        "min_character_level": 11,
        "cost": {},
        "craft_cost": {"moon_dust": 4, "spirit_pollen": 4},
        "forge_instant": False,
        "craft_seconds": 1600,
        "xp_reward": 42,
        "requires_blueprint": True,
        "result": {
            "name": "🧪 Покров луны",
            "kind": "consumable",
            "rarity": "rare",
            "use_tag": "heal_mp_pct",
            "use_value": 35,
            "summary": "Чертёж алхимика.",
        },
    },
),

_reg(
    {
        "id": "bp_al_phoenix_breath",
        "name_ru": "Чертёж: дыхание феникса",
        "description": "Цветок феникса.",
        "profession": "alchemist",
        "min_profession_level": 11,
        "min_station_level": 2,
        "min_character_level": 13,
        "cost": {},
        "craft_cost": {"blue_berry": 5, "mandrake_root": 3, "phoenix_flower": 3},
        "forge_instant": False,
        "craft_seconds": 2200,
        "xp_reward": 50,
        "requires_blueprint": True,
        "result": {
            "name": "🧪 Дыхание феникса",
            "kind": "consumable",
            "rarity": "epic",
            "use_tag": "heal_hp_pct",
            "use_value": 48,
            "summary": "Чертёж алхимика.",
        },
    },
),

_reg(
    {
        "id": "bp_al_void_philter",
        "name_ru": "Чертёж: фильтр бездны",
        "description": "Эссенция бездны.",
        "profession": "alchemist",
        "min_profession_level": 13,
        "min_station_level": 3,
        "min_character_level": 14,
        "cost": {},
        "craft_cost": {"moon_dust": 4, "void_essence": 2, "void_rose_thorn": 3},
        "forge_instant": False,
        "craft_seconds": 3000,
        "xp_reward": 62,
        "requires_blueprint": True,
        "result": {
            "name": "🧪 Фильтр бездны",
            "kind": "consumable",
            "rarity": "epic",
            "use_tag": "heal_mp_pct",
            "use_value": 42,
            "summary": "Чертёж алхимика.",
        },
    },
),

_reg(
    {
        "id": "bp_al_basilisk_brew",
        "name_ru": "Чертёж: отвар василиска",
        "description": "Чешуя.",
        "profession": "alchemist",
        "min_profession_level": 10,
        "min_station_level": 2,
        "min_character_level": 12,
        "cost": {},
        "craft_cost": {"basilisk_scale": 5, "golem_tear": 3},
        "forge_instant": False,
        "craft_seconds": 2000,
        "xp_reward": 46,
        "requires_blueprint": True,
        "result": {
            "name": "🧪 Отвар василиска",
            "kind": "consumable",
            "rarity": "rare",
            "use_tag": "heal_hp_pct",
            "use_value": 45,
            "summary": "Чертёж алхимика.",
        },
    },
),

_reg(
    {
        "id": "bp_al_starlight_serum",
        "name_ru": "Чертёж: сыворотка звездного света",
        "description": "Лунная пыль.",
        "profession": "alchemist",
        "min_profession_level": 12,
        "min_station_level": 3,
        "min_character_level": 14,
        "cost": {},
        "craft_cost": {"moon_dust": 5, "phoenix_flower": 2, "void_rose_thorn": 3},
        "forge_instant": False,
        "craft_seconds": 2800,
        "xp_reward": 58,
        "requires_blueprint": True,
        "result": {
            "name": "🧪 Сыворотка звездного света",
            "kind": "consumable",
            "rarity": "epic",
            "use_tag": "heal_hp_pct",
            "use_value": 52,
            "summary": "Чертёж алхимика.",
        },
    },
),

_reg(
    {
        "id": "bp_al_golden_dawn",
        "name_ru": "Чертёж: золотой рассвет",
        "description": "Золотое яблоко.",
        "profession": "alchemist",
        "min_profession_level": 18,
        "min_station_level": 4,
        "min_character_level": 17,
        "cost": {},
        "craft_cost": {"golden_apple": 1, "phoenix_flower": 2, "void_essence": 3},
        "forge_instant": False,
        "craft_seconds": 6000,
        "xp_reward": 95,
        "requires_blueprint": True,
        "result": {
            "name": "🧪 Золотой рассвет",
            "kind": "consumable",
            "rarity": "legendary",
            "use_tag": "heal_hp_pct",
            "use_value": 75,
            "summary": "Чертёж алхимика.",
        },
    },
),

_reg(
    {
        "id": "bp_al_nether_sips",
        "name_ru": "Чертёж: глотки Нижнего мира",
        "description": "Мох и роза.",
        "profession": "alchemist",
        "min_profession_level": 4,
        "min_station_level": 1,
        "min_character_level": 6,
        "cost": {},
        "craft_cost": {"meadow_herb": 5, "moss_fungus": 6, "void_rose_thorn": 1},
        "forge_instant": False,
        "craft_seconds": 700,
        "xp_reward": 24,
        "requires_blueprint": True,
        "result": {
            "name": "🧪 Глотки Нижнего мира",
            "kind": "consumable",
            "rarity": "uncommon",
            "use_tag": "heal_mp_pct",
            "use_value": 22,
            "summary": "Чертёж алхимика.",
        },
    },
),

_reg(
    {
        "id": "bp_al_abyss_ink",
        "name_ru": "Чертёж: чернила Бездны",
        "description": "Смола на броню.",
        "profession": "alchemist",
        "min_profession_level": 7,
        "min_station_level": 2,
        "min_character_level": 9,
        "cost": {},
        "craft_cost": {"basilisk_scale": 2, "mandrake_root": 3, "void_rose_thorn": 4},
        "forge_instant": False,
        "craft_seconds": 1300,
        "xp_reward": 36,
        "requires_blueprint": True,
        "result": {
            "name": "🧪 Чернила Бездны",
            "kind": "consumable",
            "rarity": "rare",
            "use_tag": "workshop_alchemy_enchant",
            "alchemy_enchant_armor": True,
            "add_fire_resist_pct": 8,
            "enchant_label_ru": "Бездна I",
            "summary": "Чертёж: смола на броню.",
        },
    },
),

_reg(
    {
        "id": "bp_al_sun_tears",
        "name_ru": "Чертёж: слёзы солнца",
        "description": "Золотое яблоко.",
        "profession": "alchemist",
        "min_profession_level": 20,
        "min_station_level": 4,
        "min_character_level": 18,
        "cost": {},
        "craft_cost": {"golden_apple": 2, "moon_dust": 5, "void_essence": 2},
        "forge_instant": False,
        "craft_seconds": 6400,
        "xp_reward": 102,
        "requires_blueprint": True,
        "result": {
            "name": "🧪 Слёзы солнца",
            "kind": "consumable",
            "rarity": "legendary",
            "use_tag": "heal_hp_pct",
            "use_value": 80,
            "summary": "Чертёж алхимика.",
        },
    },
),

_reg(
    {
        "id": "bp_al_witch_honey",
        "name_ru": "Чертёж: мёд ведьмы",
        "description": "Травы.",
        "profession": "alchemist",
        "min_profession_level": 6,
        "min_station_level": 1,
        "min_character_level": 8,
        "cost": {},
        "craft_cost": {"mandrake_root": 4, "meadow_herb": 6, "spirit_pollen": 3},
        "forge_instant": False,
        "craft_seconds": 1100,
        "xp_reward": 32,
        "requires_blueprint": True,
        "result": {
            "name": "🧪 Мёд ведьмы",
            "kind": "consumable",
            "rarity": "uncommon",
            "use_tag": "heal_hp_pct",
            "use_value": 36,
            "summary": "Чертёж алхимика.",
        },
    },
),

_reg(
    {
        "id": "bp_al_oracle_tea",
        "name_ru": "Чертёж: чай оракула",
        "description": "Лунная пыль.",
        "profession": "alchemist",
        "min_profession_level": 15,
        "min_station_level": 3,
        "min_character_level": 15,
        "cost": {},
        "craft_cost": {"basilisk_scale": 3, "moon_dust": 4, "void_essence": 1},
        "forge_instant": False,
        "craft_seconds": 3400,
        "xp_reward": 70,
        "requires_blueprint": True,
        "result": {
            "name": "🧪 Чай оракула",
            "kind": "consumable",
            "rarity": "epic",
            "use_tag": "heal_mp_pct",
            "use_value": 38,
            "summary": "Чертёж алхимика.",
        },
    },
),

_reg(
    {
        "id": "bp_jw_pearl_ring",
        "name_ru": "Чертёж: перстень речной жемчужины",
        "description": "Жемчужина.",
        "profession": "jeweler",
        "min_profession_level": 2,
        "min_station_level": 1,
        "min_character_level": 3,
        "cost": {},
        "craft_cost": {"copper_dust": 4, "river_pearl": 5},
        "forge_instant": False,
        "craft_seconds": 500,
        "xp_reward": 16,
        "requires_blueprint": True,
        "result": {
            "name": "💍 Перстень речной жемчужины",
            "kind": "ring",
            "rarity": "common",
            "defense": 4,
            "int": 3,
            "summary": "Чертёж ювелира.",
        },
    },
),

_reg(
    {
        "id": "bp_jw_tiger_amulet",
        "name_ru": "Чертёж: амулет тигрового глаза",
        "description": "Тигровый глаз.",
        "profession": "jeweler",
        "min_profession_level": 4,
        "min_station_level": 1,
        "min_character_level": 6,
        "cost": {},
        "craft_cost": {"amber": 4, "tiger_eye": 5},
        "forge_instant": False,
        "craft_seconds": 900,
        "xp_reward": 24,
        "requires_blueprint": True,
        "result": {
            "name": "📿 Амулет тигрового глаза",
            "kind": "amulet",
            "rarity": "uncommon",
            "defense": 14,
            "dex": 5,
            "summary": "Чертёж ювелира.",
        },
    },
),

_reg(
    {
        "id": "bp_jw_moon_band",
        "name_ru": "Чертёж: лунное кольцо",
        "description": "Лунный камень.",
        "profession": "jeweler",
        "min_profession_level": 5,
        "min_station_level": 1,
        "min_character_level": 7,
        "cost": {},
        "craft_cost": {"moonstone": 5, "river_pearl": 3},
        "forge_instant": False,
        "craft_seconds": 1000,
        "xp_reward": 28,
        "requires_blueprint": True,
        "result": {
            "name": "💍 Лунное кольцо",
            "kind": "ring",
            "rarity": "uncommon",
            "defense": 8,
            "int": 7,
            "summary": "Чертёж ювелира.",
        },
    },
),

_reg(
    {
        "id": "bp_jw_ruby_signet",
        "name_ru": "Чертёж: кровавая печать",
        "description": "Рубин.",
        "profession": "jeweler",
        "min_profession_level": 7,
        "min_station_level": 2,
        "min_character_level": 9,
        "cost": {},
        "craft_cost": {"blood_ruby": 4, "copper_dust": 5},
        "forge_instant": False,
        "craft_seconds": 1600,
        "xp_reward": 38,
        "requires_blueprint": True,
        "result": {
            "name": "💍 Кровавая печать",
            "kind": "ring",
            "rarity": "rare",
            "defense": 12,
            "str": 6,
            "summary": "Чертёж ювелира.",
        },
    },
),

_reg(
    {
        "id": "bp_jw_storm_pendant",
        "name_ru": "Чертёж: медальон бури",
        "description": "Сапфир бури.",
        "profession": "jeweler",
        "min_profession_level": 9,
        "min_station_level": 2,
        "min_character_level": 11,
        "cost": {},
        "craft_cost": {"moonstone": 3, "storm_sapphire": 4},
        "forge_instant": False,
        "craft_seconds": 2100,
        "xp_reward": 46,
        "requires_blueprint": True,
        "result": {
            "name": "📿 Медальон бури",
            "kind": "amulet",
            "rarity": "rare",
            "defense": 18,
            "int": 8,
            "summary": "Чертёж ювелира.",
        },
    },
),

_reg(
    {
        "id": "bp_jw_life_circle",
        "name_ru": "Чертёж: кольцо жизни",
        "description": "Изумруд.",
        "profession": "jeweler",
        "min_profession_level": 8,
        "min_station_level": 2,
        "min_character_level": 10,
        "cost": {},
        "craft_cost": {"amber": 4, "life_emerald": 4},
        "forge_instant": False,
        "craft_seconds": 1900,
        "xp_reward": 44,
        "requires_blueprint": True,
        "result": {
            "name": "💍 Кольцо жизни",
            "kind": "ring",
            "rarity": "rare",
            "defense": 11,
            "vit": 10,
            "summary": "Чертёж ювелира.",
        },
    },
),

_reg(
    {
        "id": "bp_jw_black_opal_orb",
        "name_ru": "Чертёж: сфера чёрного опала",
        "description": "Чёрный опал.",
        "profession": "jeweler",
        "min_profession_level": 12,
        "min_station_level": 3,
        "min_character_level": 13,
        "cost": {},
        "craft_cost": {"black_opal": 5, "tiger_eye": 4},
        "forge_instant": False,
        "craft_seconds": 2800,
        "xp_reward": 56,
        "requires_blueprint": True,
        "result": {
            "name": "🔮 Сфера чёрного опала",
            "kind": "ring",
            "rarity": "epic",
            "defense": 16,
            "int": 12,
            "summary": "Чертёж ювелира.",
        },
    },
),

_reg(
    {
        "id": "bp_jw_void_diadem",
        "name_ru": "Чертёж: диадема пустоты",
        "description": "Алмаз пустоты.",
        "profession": "jeweler",
        "min_profession_level": 14,
        "min_station_level": 3,
        "min_character_level": 15,
        "cost": {},
        "craft_cost": {"black_opal": 3, "void_diamond": 4},
        "forge_instant": False,
        "craft_seconds": 3600,
        "xp_reward": 66,
        "requires_blueprint": True,
        "result": {
            "name": "📿 Диадема пустоты",
            "kind": "amulet",
            "rarity": "epic",
            "defense": 22,
            "dex": 10,
            "summary": "Чертёж ювелира.",
        },
    },
),

_reg(
    {
        "id": "bp_jw_cyclops_band",
        "name_ru": "Чертёж: кольцо ока циклопа",
        "description": "Глаз циклопа.",
        "profession": "jeweler",
        "min_profession_level": 16,
        "min_station_level": 3,
        "min_character_level": 16,
        "cost": {},
        "craft_cost": {"cyclops_eye": 2, "life_emerald": 3, "storm_sapphire": 4},
        "forge_instant": False,
        "craft_seconds": 4200,
        "xp_reward": 76,
        "requires_blueprint": True,
        "result": {
            "name": "💍 Кольцо ока циклопа",
            "kind": "ring",
            "rarity": "legendary",
            "defense": 18,
            "int": 14,
            "summary": "Чертёж ювелира.",
        },
    },
),

_reg(
    {
        "id": "bp_jw_starheart_locket",
        "name_ru": "Чертёж: медальон сердца звезды",
        "description": "Сердце звезды.",
        "profession": "jeweler",
        "min_profession_level": 19,
        "min_station_level": 4,
        "min_character_level": 18,
        "cost": {},
        "craft_cost": {"cyclops_eye": 1, "star_heart": 1, "void_diamond": 3},
        "forge_instant": False,
        "craft_seconds": 6200,
        "xp_reward": 98,
        "requires_blueprint": True,
        "result": {
            "name": "📿 Медальон сердца звезды",
            "kind": "amulet",
            "rarity": "legendary",
            "defense": 26,
            "vit": 14,
            "summary": "Чертёж ювелира.",
        },
    },
),

_reg(
    {
        "id": "bp_jw_amber_weave",
        "name_ru": "Чертёж: янтарное переплетение",
        "description": "Янтарь.",
        "profession": "jeweler",
        "min_profession_level": 6,
        "min_station_level": 1,
        "min_character_level": 8,
        "cost": {},
        "craft_cost": {"amber": 6, "tiger_eye": 5},
        "forge_instant": False,
        "craft_seconds": 1200,
        "xp_reward": 30,
        "requires_blueprint": True,
        "result": {
            "name": "💍 Янтарное переплетение",
            "kind": "ring",
            "rarity": "uncommon",
            "defense": 9,
            "dex": 7,
            "summary": "Чертёж ювелира.",
        },
    },
),

_reg(
    {
        "id": "bp_jw_crimson_loop",
        "name_ru": "Чертёж: багряная петля",
        "description": "Рубин и сапфир.",
        "profession": "jeweler",
        "min_profession_level": 11,
        "min_station_level": 2,
        "min_character_level": 12,
        "cost": {},
        "craft_cost": {"blood_ruby": 3, "moonstone": 3, "storm_sapphire": 3},
        "forge_instant": False,
        "craft_seconds": 2400,
        "xp_reward": 50,
        "requires_blueprint": True,
        "result": {
            "name": "💍 Багряная петля",
            "kind": "ring",
            "rarity": "epic",
            "defense": 14,
            "str": 10,
            "summary": "Чертёж ювелира.",
        },
    },
),

_reg(
    {
        "id": "bp_jw_emerald_gaze",
        "name_ru": "Чертёж: изумрудный взгляд",
        "description": "Изумруд.",
        "profession": "jeweler",
        "min_profession_level": 10,
        "min_station_level": 2,
        "min_character_level": 12,
        "cost": {},
        "craft_cost": {"life_emerald": 5, "river_pearl": 4},
        "forge_instant": False,
        "craft_seconds": 2300,
        "xp_reward": 48,
        "requires_blueprint": True,
        "result": {
            "name": "📿 Изумрудный взгляд",
            "kind": "amulet",
            "rarity": "rare",
            "defense": 20,
            "vit": 12,
            "summary": "Чертёж ювелира.",
        },
    },
),

_reg(
    {
        "id": "bp_jw_copper_coronet",
        "name_ru": "Чертёж: медная диадема",
        "description": "Медная крошка.",
        "profession": "jeweler",
        "min_profession_level": 3,
        "min_station_level": 1,
        "min_character_level": 5,
        "cost": {},
        "craft_cost": {"copper_dust": 10, "river_pearl": 4},
        "forge_instant": False,
        "craft_seconds": 700,
        "xp_reward": 22,
        "requires_blueprint": True,
        "result": {
            "name": "📿 Медная диадема",
            "kind": "amulet",
            "rarity": "common",
            "defense": 11,
            "summary": "Чертёж ювелира.",
        },
    },
),

_reg(
    {
        "id": "bp_jw_opal_chain",
        "name_ru": "Чертёж: цепь опалов",
        "description": "Чёрный опал.",
        "profession": "jeweler",
        "min_profession_level": 13,
        "min_station_level": 3,
        "min_character_level": 14,
        "cost": {},
        "craft_cost": {"amber": 3, "black_opal": 4, "moonstone": 4},
        "forge_instant": False,
        "craft_seconds": 3200,
        "xp_reward": 60,
        "requires_blueprint": True,
        "result": {
            "name": "📿 Цепь опалов",
            "kind": "amulet",
            "rarity": "epic",
            "defense": 24,
            "int": 11,
            "summary": "Чертёж ювелира.",
        },
    },
),
]

extend_recipes_with_alchemy_enchant_scrolls(_reg, _RECIPES_LIST)

RECIPES: tuple[dict[str, Any], ...] = tuple(_RECIPES_LIST)


def get_recipe_by_id(recipe_id: str) -> dict[str, Any] | None:
    return _RECIPE_BY_ID.get(str(recipe_id).strip())


def recipes_for_profession(profession: str) -> list[dict[str, Any]]:
    p = str(profession).strip().lower()
    return [r for r in RECIPES if str(r.get("profession", "")).strip().lower() == p]


def is_forge_instant(recipe: dict[str, Any]) -> bool:
    return bool(recipe.get("forge_instant"))


def forge_recipes_only() -> list[dict[str, Any]]:
    return [r for r in RECIPES if is_forge_instant(r)]


def max_station_level_cap(prof_level: int) -> int:
    """Макс. уровень станка при данном уровне профессии (1..5)."""
    pl = max(1, int(prof_level))
    return min(5, 1 + max(0, pl - 1) // 5)


def xp_to_next_profession_level(level: int, profession: str) -> int:
    """Опыт до следующего уровня профессии (счётчик prof_xp)."""
    pk = str(profession).strip().lower()
    cap = max_profession_level(pk)
    lv = max(1, int(level))
    if lv >= cap:
        return 0
    if pk == PROF_BLACKSMITH:
        base, step = 85, 20
    else:
        base, step = 95, 24
    return base + (lv - 1) * step