"""initial_all_tables

Revision ID: 8a9b3037bda5
Revises: 
Create Date: 2026-04-13 17:32:57.013842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8a9b3037bda5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('is_banned', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('muted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('admin_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), server_default=sa.text("'INFO'"), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_logs_action'), 'admin_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_logs_actor_telegram_id'), 'admin_logs', ['actor_telegram_id'], unique=False)
    op.create_index(op.f('ix_admin_logs_created_at'), 'admin_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_logs_target_user_id'), 'admin_logs', ['target_user_id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('class_key', sa.String(length=32), nullable=False),
    sa.Column('stat_strength', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stat_dexterity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stat_intelligence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stat_vitality', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stat_luck', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hp_current', sa.Integer(), server_default='1', nullable=False),
    sa.Column('hp_max', sa.Integer(), server_default='1', nullable=False),
    sa.Column('mp_current', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mp_max', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stamina', sa.Integer(), server_default='20', nullable=False),
    sa.Column('last_stamina_regen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('floor_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('experience', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('gold', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('rune_stones', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active_title', sa.String(length=64), nullable=True),
    sa.Column('element', sa.String(length=24), nullable=True),
    sa.Column('total_kills', sa.Integer(), server_default='0', nullable=False),
    sa.Column('death_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tavern_visits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enchant_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('runes_socketed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('meta_progress', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_characters_floor_number'), 'characters', ['floor_number'], unique=False)
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=True)
    op.create_table('floor_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('visits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mini_boss_defeated', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('boss_defeated', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('secret_rooms_found', sa.Integer(), server_default='0', nullable=False),
    sa.Column('extra', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'floor_number', name='uq_floor_progress_char_floor')
    )
    op.create_index(op.f('ix_floor_progress_character_id'), 'floor_progress', ['character_id'], unique=False)
    op.create_index(op.f('ix_floor_progress_floor_number'), 'floor_progress', ['floor_number'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('equip_slot', sa.String(length=32), nullable=True),
    sa.Column('bag_slot', sa.Integer(), nullable=True),
    sa.Column('item_data', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_character_id'), 'inventory_items', ['character_id'], unique=False)
    op.create_table('quest_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('quest_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'quest_key', name='uq_quest_progress_char_key')
    )
    op.create_index(op.f('ix_quest_progress_character_id'), 'quest_progress', ['character_id'], unique=False)
    op.create_index(op.f('ix_quest_progress_quest_key'), 'quest_progress', ['quest_key'], unique=False)
    op.create_table('enchant_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('old_level', sa.Integer(), server_default='0', nullable=False),
    sa.Column('new_level', sa.Integer(), server_default='0', nullable=False),
    sa.Column('success', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('destroyed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('cost_gold', sa.Integer(), server_default='0', nullable=False),
    sa.Column('extra', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enchant_logs_character_id'), 'enchant_logs', ['character_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enchant_logs_character_id'), table_name='enchant_logs')
    op.drop_table('enchant_logs')
    op.drop_index(op.f('ix_quest_progress_quest_key'), table_name='quest_progress')
    op.drop_index(op.f('ix_quest_progress_character_id'), table_name='quest_progress')
    op.drop_table('quest_progress')
    op.drop_index(op.f('ix_inventory_items_character_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_floor_progress_floor_number'), table_name='floor_progress')
    op.drop_index(op.f('ix_floor_progress_character_id'), table_name='floor_progress')
    op.drop_table('floor_progress')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_floor_number'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_admin_logs_target_user_id'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_created_at'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_actor_telegram_id'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_action'), table_name='admin_logs')
    op.drop_table('admin_logs')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
